import "vuetify/styles";
import "@mdi/font/css/materialdesignicons.css";
import { createVuetify } from "vuetify";

export default createVuetify({
  theme: {
    defaultTheme: "light",
    themes: {
      light: {
        dark: false,
        colors: {
          primary: "#006B5F",
          "on-primary": "#FFFFFF",
          "primary-container": "#00FEE5",
          "on-primary-container": "#005048",
          secondary: "#386569",
          "on-secondary": "#FFFFFF",
          "secondary-container": "#BCEBEE",
          "on-secondary-container": "#1E4D51",
          tertiary: "#216678",
          "on-tertiary": "#FFFFFF",
          "tertiary-container": "#B1ECFF",
          "on-tertiary-container": "#004E5E",
          background: "#EEFDF8",
          "on-background": "#111E1C",
          surface: "#FFFFFF",
          "on-surface": "#111E1C",
          "surface-variant": "#D4E7E2",
          "on-surface-variant": "#394A47",
          outline: "#697B77",
          "outline-variant": "#B8CAC6",
          "surface-tint": "#006B5F",
          error: "#BA1A1A",
          "on-error": "#FFFFFF",
          "error-container": "#FFDAD6",
          "on-error-container": "#93000A",
          warning: "#F57C00",
          success: "#2E7D32",
        },
      },
      dark: {
        dark: true,
        colors: {
          primary: "#00DEC9",
          "on-primary": "#003731",
          "primary-container": "#005048",
          "on-primary-container": "#00FEE5",
          secondary: "#A0CFD2",
          "on-secondary": "#00373A",
          "secondary-container": "#1E4D51",
          "on-secondary-container": "#BCEBEE",
          tertiary: "#91D0E4",
          "on-tertiary": "#003641",
          "tertiary-container": "#004E5E",
          "on-tertiary-container": "#B1ECFF",
          background: "#091613",
          "on-background": "#D7E6E1",
          surface: "#191C22",
          "on-surface": "#D7E6E1",
          "surface-variant": "#394A47",
          "on-surface-variant": "#B8CAC6",
          outline: "#829490",
          "outline-variant": "#394A47",
          "surface-tint": "#00DEC9",
          error: "#FFB4AB",
          "on-error": "#690005",
          "error-container": "#93000A",
          "on-error-container": "#FFDAD6",
          warning: "#FFB74D",
          success: "#81C784",
        },
      },
    },
  },
});
